services:
  # Banco de Dados
  db:
    image: postgres:16-alpine
    container_name: ecocity_postgres
    restart: always
    environment:
      POSTGRES_DB: ecocitydb
      POSTGRES_USER: ecocity_admin
      POSTGRES_PASSWORD: esg_secure_pass_2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecocity_network

  # Backend API
  backend:
    build: ./backend
    container_name: ecocity_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecocitydb
      SPRING_DATASOURCE_USERNAME: ecocity_admin
      SPRING_DATASOURCE_PASSWORD: esg_secure_pass_2026
    depends_on:
      - db
    networks:
      - ecocity_network

  # Frontend Dashboard
  frontend:
    build: ./frontend
    container_name: ecocity_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecocity_network

volumes:
  pgdata:

networks:
  ecocity_network:
    driver: bridge