spring.application.name=api
# Nome da Aplicação
spring.application.name=EcoCity Monitor API

# Configuração do PostgreSQL (Aponta para o localhost quando rodando fora do Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecocitydb
spring.datasource.username=ecocity_admin
spring.datasource.password=esg_secure_pass_2026

# Hibernate (Atualiza a estrutura das tabelas automaticamente no ambiente de dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect